### ISSUE TITLE
source building failure on osx 10.11.5 (15F34)

### ISSUE THREAD

**Issue by bung87** [mapycz/mapnik#1] opened 2016-11-09 08:08 UTC
source building failure

```
include/mapnik/text/placement_finder_impl.hpp:38:22: error: variable has incomplete type
      'mapnik::vertex_cache'
        vertex_cache pp(ec);
                     ^
include/mapnik/text/placement_finder_impl.hpp:42:18: error: variable has incomplete type
      'mapnik::vertex_cache'
    vertex_cache pp(path);
                 ^
```

**Comment by talaj** [comment] 2016-11-09 09:34
Thanks for noticing, it's now fixed in master.

The problem only manifested with clang compiler.

**Comment by bung87** [comment] 2016-11-09 11:10
thanks for response.another problem occurs.

```
"boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const", referenced from:
      std::__1::__wrap_iter<char const*> boost::re_detail_106000::re_is_set_member<std::__1::__wrap_iter<char const*>, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>, boost::re_detail_106000::re_set_long<unsigned int> const*, boost::re_detail_106000::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool) in expression_node.os
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [src/libmapnik.dylib] Error 1
scons: building terminated because of errors.
make: *** [install] Error 2
```

according to https://github.com/mapnik/mapnik/wiki/InstallationTroubleshooting#permission-denied-error,I simplely run `sudo python scons/scons.py install` and `make install` agains,
no error occurs,since I just new to mapnik have no knowlege to know whether installation is correct or not.I just run `make test` ,get this results below,this may help something.

`Visual rendering: 20 failed / 1906 passed / 0 overwritten / 0 errors`

**Comment by talaj** [comment] 2016-11-09 11:32
Unfortunately, that error is probably OS X specific. I'm not able to reproduce it on Linux.

However, if you got `20 failed / 1906 passed` it seems that things work mostly well.

You can take a look on complete visual test report in 

```
/tmp/mapnik-visual-images/visual-test-results/index.html
```

on your machine. I hope you will find only non-visual differences.

**Comment by talaj** [comment] 2016-11-09 11:48
Also, if you don't need [specific features](https://github.com/mapycz/mapnik#mapycz-mapnik) of this fork of Mapnik, I would recommend to use upstream version of Mapnik, which is well tested in OS X environment: [github.com/mapnik/mapnik](https://github.com/mapnik/mapnik).

**Comment by bung87** [comment] 2016-11-09 13:13
I have checked the test report,all picture looks as well.I just stuck in https://github.com/tilemill-project/tilemill building process,and try to build the **mapnik** from source as **tilemill** depens on it(I assumed it at that time).after some works I finally decide to install it through brew and seems works ok.your repository version building much easier than upstream version.and after all these dependency problems solved, I figure out it is **node-mapnick** related problem.Thanks again for you advice!

**Comment by talaj** [comment] 2016-11-10 08:50
OK, so if you don't mind I'm closing this issue now.

**Closed as completed by talaj** 2016-11-10 08:50 UTC
